version: '2.3'

services:
  weeb-db:
    image: healthcheck/postgres
    container_name: weeb-db
    env_file:
      - ../config/.env.postgres
    volumes:
      - weeb-db-data:/var/lib/postgresql/data/
    ports:
      - 50000:5432
    restart: unless-stopped

  weeb-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: weeb-app
    restart: unless-stopped
    depends_on:
      weeb-db:
        condition: service_healthy
    volumes:
      - ..:/app

volumes:
  weeb-db-data:
    driver: local
