version: '2.3'

services:
  weeb-db:
    image: healthcheck/postgres
    container_name: weeb-db
    env_file:
      - ./config/.env.postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    restart: unless-stopped

  weeb-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: snowsailor/test:latest
    container_name: weeb-app
    restart: unless-stopped
    depends_on:
      weeb-db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db-data:
    driver: local
